// ─────────────────────────────────────────────────────────────────────────────
// LEADERBOARD PERSONALITIES
// A curated roster of real, globally-recognised figures across investing, hedge
// funds, private equity, venture capital, banking, quant/trading, entrepreneurship,
// economics, mathematics and computer science. Every entry is a real person.
//
// `xp` is a success-weighted score (NOT an official metric) used only to rank the
// board so the user can climb through it over time. Values are Claude's estimates
// of relative impact/achievement, tiered roughly as:
//   900k–1M  living-legend / GOAT      250k–500k  elite
//   500k–850k legend                   100k–250k  notable
//   20k–90k   rising / niche
// ─────────────────────────────────────────────────────────────────────────────

const P = (name, domain, country, xp, note) => ({ name, domain, country, xp, note });

export const PERSONALITIES = [
  // ── Legendary investors ──────────────────────────────────────────────
  P('Warren Buffett', 'Investing', 'United States', 1000000, 'CEO of Berkshire Hathaway; the most successful investor of all time'),
  P('Charlie Munger', 'Investing', 'United States', 880000, 'Vice-Chairman of Berkshire Hathaway; mental-models investor'),
  P('Benjamin Graham', 'Investing', 'United States', 820000, 'Father of value investing; author of The Intelligent Investor'),
  P('Peter Lynch', 'Investing', 'United States', 620000, 'Ran Fidelity Magellan to legendary returns'),
  P('John Templeton', 'Investing', 'United States', 560000, 'Pioneer of global contrarian investing'),
  P('Philip Fisher', 'Investing', 'United States', 480000, 'Growth-investing pioneer; Common Stocks and Uncommon Profits'),
  P('John Bogle', 'Investing', 'United States', 700000, 'Founder of Vanguard; invented the index fund'),
  P('Bill Miller', 'Investing', 'United States', 300000, 'Beat the S&P 500 for 15 straight years at Legg Mason'),
  P('Mohnish Pabrai', 'Investing', 'United States', 180000, 'Value investor; Dhandho Investor'),
  P('Guy Spier', 'Investing', 'Switzerland', 140000, 'Aquamarine Fund; The Education of a Value Investor'),
  P('Joel Greenblatt', 'Investing', 'United States', 320000, 'Gotham Capital; the Magic Formula'),
  P('Seth Klarman', 'Investing', 'United States', 560000, 'Baupost Group; author of Margin of Safety'),
  P('Howard Marks', 'Investing', 'United States', 560000, 'Co-founder of Oaktree Capital; market-cycle sage'),
  P('Mario Gabelli', 'Investing', 'United States', 300000, 'Founder of GAMCO Investors'),
  P('Bill Ackman', 'Hedge Funds', 'United States', 520000, 'Founder of Pershing Square Capital'),
  P('Prem Watsa', 'Investing', 'Canada', 260000, 'Founder of Fairfax; "Canada\'s Warren Buffett"'),
  P('Thomas Rowe Price Jr.', 'Investing', 'United States', 320000, 'Father of growth investing; founder of T. Rowe Price'),
  P('Shelby Davis', 'Investing', 'United States', 240000, 'Turned $50k into $900M over decades'),
  P('Walter Schloss', 'Investing', 'United States', 220000, 'Deep-value disciple of Ben Graham'),
  P('Chuck Akre', 'Investing', 'United States', 160000, 'Akre Capital; the "three-legged stool"'),
  P('Nick Sleep', 'Investing', 'United Kingdom', 150000, 'Nomad Investment Partnership'),
  P('Terry Smith', 'Investing', 'United Kingdom', 210000, 'Founder of Fundsmith'),
  P('Anthony Bolton', 'Investing', 'United Kingdom', 200000, 'Fidelity Special Situations legend'),

  // ── Hedge fund titans ────────────────────────────────────────────────
  P('Ray Dalio', 'Hedge Funds', 'United States', 900000, 'Founder of Bridgewater Associates, the largest hedge fund'),
  P('George Soros', 'Hedge Funds', 'United States', 900000, 'Broke the Bank of England; Quantum Fund'),
  P('Jim Simons', 'Quant / Trading', 'United States', 980000, 'Renaissance Technologies; the greatest quant ever'),
  P('Ken Griffin', 'Hedge Funds', 'United States', 820000, 'Founder & CEO of Citadel'),
  P('Steve Cohen', 'Hedge Funds', 'United States', 720000, 'Founder of Point72 / SAC Capital'),
  P('Stanley Druckenmiller', 'Hedge Funds', 'United States', 780000, 'Duquesne Capital; never had a down year'),
  P('Paul Tudor Jones', 'Hedge Funds', 'United States', 640000, 'Founder of Tudor Investment; called the 1987 crash'),
  P('David Tepper', 'Hedge Funds', 'United States', 620000, 'Founder of Appaloosa Management'),
  P('Carl Icahn', 'Hedge Funds', 'United States', 560000, 'Activist investor; Icahn Enterprises'),
  P('Julian Robertson', 'Hedge Funds', 'United States', 560000, 'Founder of Tiger Management; mentored the "Tiger Cubs"'),
  P('Louis Bacon', 'Hedge Funds', 'United States', 380000, 'Founder of Moore Capital Management'),
  P('Bruce Kovner', 'Hedge Funds', 'United States', 400000, 'Founder of Caxton Associates'),
  P('Michael Steinhardt', 'Hedge Funds', 'United States', 380000, 'Pioneer of the hedge fund industry'),
  P('Daniel Loeb', 'Hedge Funds', 'United States', 420000, 'Founder of Third Point'),
  P('David Einhorn', 'Hedge Funds', 'United States', 360000, 'Founder of Greenlight Capital'),
  P('John Paulson', 'Hedge Funds', 'United States', 480000, 'Made $15B shorting the 2008 housing bubble'),
  P('Ken Lasry', 'Hedge Funds', 'United States', 220000, 'Co-founder of Avenue Capital'),
  P('Marc Lasry', 'Hedge Funds', 'United States', 240000, 'Co-founder of Avenue Capital Group'),
  P('Paul Singer', 'Hedge Funds', 'United States', 460000, 'Founder of Elliott Management'),
  P('Israel Englander', 'Hedge Funds', 'United States', 520000, 'Founder of Millennium Management'),
  P('Cliff Asness', 'Quant / Trading', 'United States', 480000, 'Co-founder of AQR Capital Management'),
  P('David Shaw', 'Quant / Trading', 'United States', 560000, 'Founder of D. E. Shaw'),
  P('Leon Cooperman', 'Hedge Funds', 'United States', 300000, 'Founder of Omega Advisors'),
  P('Chase Coleman', 'Hedge Funds', 'United States', 380000, 'Founder of Tiger Global Management'),
  P('Philippe Laffont', 'Hedge Funds', 'France', 320000, 'Founder of Coatue Management'),
  P('Andreas Halvorsen', 'Hedge Funds', 'Norway', 340000, 'Co-founder of Viking Global Investors'),
  P('Chris Hohn', 'Hedge Funds', 'United Kingdom', 420000, 'Founder of TCI Fund Management'),
  P('Alan Howard', 'Hedge Funds', 'United Kingdom', 360000, 'Co-founder of Brevan Howard'),
  P('Michael Platt', 'Hedge Funds', 'United Kingdom', 380000, 'Co-founder of BlueCrest Capital'),
  P('Crispin Odey', 'Hedge Funds', 'United Kingdom', 160000, 'Founder of Odey Asset Management'),
  P('Nassim Nicholas Taleb', 'Quant / Trading', 'Lebanon', 420000, 'Black Swan theorist; tail-risk trader and author'),
  P('Ed Thorp', 'Quant / Trading', 'United States', 620000, 'Beat the dealer and the market; quant pioneer'),
  P('Jeffrey Yass', 'Quant / Trading', 'United States', 560000, 'Co-founder of Susquehanna International Group'),

  // ── Private equity & buyout ──────────────────────────────────────────
  P('Stephen Schwarzman', 'Private Equity', 'United States', 720000, 'Co-founder & CEO of Blackstone'),
  P('Henry Kravis', 'Private Equity', 'United States', 640000, 'Co-founder of KKR; pioneer of the LBO'),
  P('George Roberts', 'Private Equity', 'United States', 620000, 'Co-founder of KKR'),
  P('David Rubenstein', 'Private Equity', 'United States', 560000, 'Co-founder of The Carlyle Group'),
  P('Leon Black', 'Private Equity', 'United States', 520000, 'Co-founder of Apollo Global Management'),
  P('Marc Rowan', 'Private Equity', 'United States', 500000, 'Co-founder & CEO of Apollo Global Management'),
  P('David Bonderman', 'Private Equity', 'United States', 440000, 'Co-founder of TPG Capital'),
  P('Jonathan Gray', 'Private Equity', 'United States', 480000, 'President & COO of Blackstone; real-estate mastermind'),
  P('Orlando Bravo', 'Private Equity', 'United States', 460000, 'Founder of Thoma Bravo; software buyout king'),
  P('Robert F. Smith', 'Private Equity', 'United States', 480000, 'Founder of Vista Equity Partners'),
  P('Joseph Bae', 'Private Equity', 'United States', 320000, 'Co-CEO of KKR'),
  P('Scott Nuttall', 'Private Equity', 'United States', 320000, 'Co-CEO of KKR'),
  P('Nelson Peltz', 'Private Equity', 'United States', 300000, 'Founder of Trian Partners'),
  P('Guy Hands', 'Private Equity', 'United Kingdom', 220000, 'Founder of Terra Firma Capital Partners'),
  P('Lionel Assant', 'Private Equity', 'France', 180000, 'Global co-CIO of Blackstone'),

  // ── Venture capital ──────────────────────────────────────────────────
  P('John Doerr', 'Venture Capital', 'United States', 560000, 'Chairman of Kleiner Perkins; backed Google & Amazon'),
  P('Michael Moritz', 'Venture Capital', 'United Kingdom', 520000, 'Sequoia Capital; backed Google, Yahoo, PayPal'),
  P('Don Valentine', 'Venture Capital', 'United States', 520000, 'Founder of Sequoia Capital'),
  P('Arthur Rock', 'Venture Capital', 'United States', 480000, 'Financed Intel & Apple; coined "venture capital"'),
  P('Peter Thiel', 'Venture Capital', 'United States', 700000, 'Co-founder of PayPal & Palantir; first Facebook investor'),
  P('Marc Andreessen', 'Venture Capital', 'United States', 620000, 'Co-founder of Netscape and Andreessen Horowitz'),
  P('Ben Horowitz', 'Venture Capital', 'United States', 420000, 'Co-founder of Andreessen Horowitz'),
  P('Vinod Khosla', 'Venture Capital', 'United States', 460000, 'Co-founder of Sun Microsystems; founder of Khosla Ventures'),
  P('Bill Gurley', 'Venture Capital', 'United States', 360000, 'Benchmark; early Uber backer'),
  P('Mary Meeker', 'Venture Capital', 'United States', 340000, 'Queen of the Internet; founder of Bond Capital'),
  P('Fred Wilson', 'Venture Capital', 'United States', 280000, 'Co-founder of Union Square Ventures'),
  P('Reid Hoffman', 'Venture Capital', 'United States', 480000, 'Co-founder of LinkedIn; partner at Greylock'),
  P('Yuri Milner', 'Venture Capital', 'Israel', 420000, 'Founder of DST Global; backed Facebook & Alibaba'),
  P('Masayoshi Son', 'Venture Capital', 'Japan', 620000, 'Founder of SoftBank and the Vision Fund'),
  P('Neil Shen', 'Venture Capital', 'China', 480000, 'Founding partner of Sequoia China (HongShan)'),
  P('Kathryn Kaminski', 'Quant / Trading', 'United States', 120000, 'Chief research strategist; trend-following expert'),
  P('Aileen Lee', 'Venture Capital', 'United States', 200000, 'Coined "unicorn"; founder of Cowboy Ventures'),
  P('Keith Rabois', 'Venture Capital', 'United States', 240000, 'PayPal mafia; Khosla / Founders Fund'),
  P('Alfred Lin', 'Venture Capital', 'United States', 220000, 'Sequoia; backed Airbnb & DoorDash'),
  P('Chamath Palihapitiya', 'Venture Capital', 'Canada', 220000, 'Founder of Social Capital'),

  // ── Bank, asset-manager & insurance leaders ──────────────────────────
  P('Jamie Dimon', 'Banking', 'United States', 640000, 'Chairman & CEO of JPMorgan Chase'),
  P('Larry Fink', 'Banking', 'United States', 680000, 'Co-founder & CEO of BlackRock, the largest asset manager'),
  P('Abigail Johnson', 'Banking', 'United States', 480000, 'Chairman & CEO of Fidelity Investments'),
  P('David Solomon', 'Banking', 'United States', 360000, 'CEO of Goldman Sachs'),
  P('Lloyd Blankfein', 'Banking', 'United States', 380000, 'Former CEO of Goldman Sachs'),
  P('Brian Moynihan', 'Banking', 'United States', 340000, 'CEO of Bank of America'),
  P('Jane Fraser', 'Banking', 'United States', 320000, 'CEO of Citigroup; first woman to lead a top-tier US bank'),
  P('James Gorman', 'Banking', 'Australia', 340000, 'Former CEO & Chairman of Morgan Stanley'),
  P('Stephen A. Cohen', 'Banking', 'United States', 200000, 'Financial-industry leader'),
  P('André Esteves', 'Banking', 'Brazil', 300000, 'Chairman of BTG Pactual'),
  P('Uday Kotak', 'Banking', 'India', 340000, 'Founder of Kotak Mahindra Bank'),
  P('Sergio Ermotti', 'Banking', 'Switzerland', 300000, 'CEO of UBS'),
  P('Marianne Lake', 'Banking', 'United States', 200000, 'Co-CEO of consumer banking at JPMorgan'),
  P('Anshu Jain', 'Banking', 'India', 220000, 'Former co-CEO of Deutsche Bank'),

  // ── Global entrepreneurs & magnates ──────────────────────────────────
  P('Elon Musk', 'Entrepreneurship', 'United States', 980000, 'CEO of Tesla & SpaceX; founder of xAI'),
  P('Jeff Bezos', 'Entrepreneurship', 'United States', 940000, 'Founder of Amazon and Blue Origin'),
  P('Bill Gates', 'Entrepreneurship', 'United States', 920000, 'Co-founder of Microsoft'),
  P('Steve Jobs', 'Entrepreneurship', 'United States', 940000, 'Co-founder of Apple'),
  P('Mark Zuckerberg', 'Entrepreneurship', 'United States', 820000, 'Founder & CEO of Meta'),
  P('Larry Page', 'Entrepreneurship', 'United States', 820000, 'Co-founder of Google'),
  P('Sergey Brin', 'Entrepreneurship', 'United States', 820000, 'Co-founder of Google'),
  P('Larry Ellison', 'Entrepreneurship', 'United States', 780000, 'Co-founder of Oracle'),
  P('Michael Dell', 'Entrepreneurship', 'United States', 560000, 'Founder & CEO of Dell Technologies'),
  P('Jensen Huang', 'Entrepreneurship', 'United States', 820000, 'Co-founder & CEO of NVIDIA'),
  P('Jack Ma', 'Entrepreneurship', 'China', 700000, 'Co-founder of Alibaba'),
  P('Pony Ma', 'Entrepreneurship', 'China', 640000, 'Founder & CEO of Tencent'),
  P('Zhang Yiming', 'Entrepreneurship', 'China', 620000, 'Founder of ByteDance (TikTok)'),
  P('Mukesh Ambani', 'Entrepreneurship', 'India', 700000, 'Chairman of Reliance Industries'),
  P('Gautam Adani', 'Entrepreneurship', 'India', 620000, 'Founder of the Adani Group'),
  P('Ratan Tata', 'Entrepreneurship', 'India', 560000, 'Former chairman of Tata Group'),
  P('Azim Premji', 'Entrepreneurship', 'India', 420000, 'Chairman of Wipro; philanthropist'),
  P('Narayana Murthy', 'Entrepreneurship', 'India', 420000, 'Co-founder of Infosys'),
  P('Bernard Arnault', 'Entrepreneurship', 'France', 820000, 'Chairman & CEO of LVMH'),
  P('François Pinault', 'Entrepreneurship', 'France', 440000, 'Founder of Kering / Artémis'),
  P('Amancio Ortega', 'Entrepreneurship', 'Spain', 680000, 'Founder of Inditex (Zara)'),
  P('Aliko Dangote', 'Entrepreneurship', 'Nigeria', 560000, 'Founder of Dangote Group; richest person in Africa'),
  P('Patrice Motsepe', 'Entrepreneurship', 'South Africa', 320000, 'Founder of African Rainbow Minerals'),
  P('Nassef Sawiris', 'Entrepreneurship', 'Egypt', 340000, 'CEO of OCI; Egypt\'s wealthiest businessman'),
  P('Mohammed Al Amoudi', 'Entrepreneurship', 'Saudi Arabia', 300000, 'Investor across energy and agriculture'),
  P('Prince Alwaleed bin Talal', 'Investing', 'Saudi Arabia', 440000, 'Founder of Kingdom Holding Company'),
  P('Carlos Slim', 'Entrepreneurship', 'Mexico', 640000, 'Chairman of Grupo Carso and América Móvil'),
  P('Jorge Paulo Lemann', 'Private Equity', 'Brazil', 480000, 'Co-founder of 3G Capital'),
  P('Eike Batista', 'Entrepreneurship', 'Brazil', 120000, 'Founder of the EBX Group'),
  P('Anders Holch Povlsen', 'Entrepreneurship', 'Denmark', 300000, 'Owner of Bestseller; largest ASOS shareholder'),
  P('Dietrich Mateschitz', 'Entrepreneurship', 'Austria', 340000, 'Co-founder of Red Bull'),
  P('Ingvar Kamprad', 'Entrepreneurship', 'Sweden', 460000, 'Founder of IKEA'),
  P('Richard Branson', 'Entrepreneurship', 'United Kingdom', 460000, 'Founder of the Virgin Group'),
  P('James Dyson', 'Entrepreneurship', 'United Kingdom', 360000, 'Founder & chief engineer of Dyson'),
  P('Tobi Lütke', 'Entrepreneurship', 'Canada', 340000, 'Co-founder & CEO of Shopify'),
  P('Daniel Ek', 'Entrepreneurship', 'Sweden', 380000, 'Co-founder & CEO of Spotify'),
  P('Jan Koum', 'Entrepreneurship', 'Ukraine', 300000, 'Co-founder of WhatsApp'),
  P('Sam Altman', 'Entrepreneurship', 'United States', 620000, 'CEO of OpenAI; former president of Y Combinator'),
  P('Brian Chesky', 'Entrepreneurship', 'United States', 380000, 'Co-founder & CEO of Airbnb'),
  P('Patrick Collison', 'Entrepreneurship', 'Ireland', 460000, 'Co-founder & CEO of Stripe'),
  P('John Collison', 'Entrepreneurship', 'Ireland', 440000, 'Co-founder & President of Stripe'),
  P('Travis Kalanick', 'Entrepreneurship', 'United States', 280000, 'Co-founder of Uber'),
  P('Dara Khosrowshahi', 'Management', 'United States', 300000, 'CEO of Uber; former CEO of Expedia'),
  P('Satya Nadella', 'Management', 'India', 640000, 'Chairman & CEO of Microsoft'),
  P('Sundar Pichai', 'Management', 'India', 600000, 'CEO of Alphabet and Google'),
  P('Tim Cook', 'Management', 'United States', 620000, 'CEO of Apple'),
  P('Andy Jassy', 'Management', 'United States', 380000, 'CEO of Amazon'),
  P('Lisa Su', 'Management', 'United States', 480000, 'Chair & CEO of AMD'),
  P('Reed Hastings', 'Entrepreneurship', 'United States', 460000, 'Co-founder of Netflix'),
  P('Howard Schultz', 'Entrepreneurship', 'United States', 400000, 'Built Starbucks into a global brand'),
  P('Phil Knight', 'Entrepreneurship', 'United States', 480000, 'Co-founder of Nike'),
  P('Sara Blakely', 'Entrepreneurship', 'United States', 220000, 'Founder of Spanx'),
  P('Oprah Winfrey', 'Entrepreneurship', 'United States', 400000, 'Media entrepreneur and investor'),
  P('Rihanna', 'Entrepreneurship', 'Barbados', 220000, 'Founder of Fenty Beauty'),

  // ── Economists ───────────────────────────────────────────────────────
  P('Adam Smith', 'Economics', 'United Kingdom', 700000, 'Father of modern economics; The Wealth of Nations'),
  P('John Maynard Keynes', 'Economics', 'United Kingdom', 720000, 'Founder of macroeconomics'),
  P('Milton Friedman', 'Economics', 'United States', 620000, 'Nobel laureate; monetarism'),
  P('Paul Samuelson', 'Economics', 'United States', 520000, 'First American to win the Nobel in Economics'),
  P('Friedrich Hayek', 'Economics', 'Austria', 500000, 'Nobel laureate; The Road to Serfdom'),
  P('David Ricardo', 'Economics', 'United Kingdom', 420000, 'Comparative advantage'),
  P('Kenneth Arrow', 'Economics', 'United States', 440000, 'Youngest-ever Nobel laureate in Economics'),
  P('Amartya Sen', 'Economics', 'India', 420000, 'Nobel laureate; welfare economics'),
  P('Paul Krugman', 'Economics', 'United States', 380000, 'Nobel laureate; trade theory'),
  P('Joseph Stiglitz', 'Economics', 'United States', 400000, 'Nobel laureate; information economics'),
  P('Daniel Kahneman', 'Economics', 'Israel', 520000, 'Nobel laureate; founder of behavioral economics'),
  P('Richard Thaler', 'Economics', 'United States', 400000, 'Nobel laureate; nudge theory'),
  P('Robert Shiller', 'Economics', 'United States', 380000, 'Nobel laureate; behavioral finance'),
  P('Eugene Fama', 'Economics', 'United States', 460000, 'Nobel laureate; efficient-market hypothesis'),
  P('Harry Markowitz', 'Economics', 'United States', 480000, 'Nobel laureate; modern portfolio theory'),
  P('William Sharpe', 'Economics', 'United States', 440000, 'Nobel laureate; the CAPM and Sharpe ratio'),
  P('Myron Scholes', 'Economics', 'Canada', 460000, 'Nobel laureate; Black-Scholes options model'),
  P('Robert Merton', 'Economics', 'United States', 460000, 'Nobel laureate; continuous-time finance'),
  P('Fischer Black', 'Quant / Trading', 'United States', 480000, 'Co-creator of the Black-Scholes model'),
  P('John Nash', 'Mathematics', 'United States', 620000, 'Nobel laureate; game theory; A Beautiful Mind'),
  P('Thomas Piketty', 'Economics', 'France', 340000, 'Author of Capital in the Twenty-First Century'),
  P('Esther Duflo', 'Economics', 'France', 360000, 'Nobel laureate; development economics'),
  P('Ben Bernanke', 'Economics', 'United States', 420000, 'Former Fed Chair; Nobel laureate'),
  P('Janet Yellen', 'Economics', 'United States', 420000, 'US Treasury Secretary; former Fed Chair'),
  P('Alan Greenspan', 'Economics', 'United States', 400000, 'Former Fed Chair'),
  P('Christine Lagarde', 'Economics', 'France', 420000, 'President of the European Central Bank'),
  P('Jerome Powell', 'Economics', 'United States', 380000, 'Chair of the US Federal Reserve'),
  P('Raghuram Rajan', 'Economics', 'India', 340000, 'Former RBI governor; predicted the 2008 crisis'),
  P('Mohamed El-Erian', 'Economics', 'United States', 320000, 'Former CEO of PIMCO; economic commentator'),

  // ── Mathematicians ───────────────────────────────────────────────────
  P('Isaac Newton', 'Mathematics', 'United Kingdom', 1000000, 'Co-inventor of calculus; laws of motion and gravitation'),
  P('Carl Friedrich Gauss', 'Mathematics', 'Germany', 960000, 'The Prince of Mathematicians'),
  P('Leonhard Euler', 'Mathematics', 'Switzerland', 940000, 'Most prolific mathematician in history'),
  P('Archimedes', 'Mathematics', 'Greece', 900000, 'Ancient founder of mathematical physics'),
  P('Bernhard Riemann', 'Mathematics', 'Germany', 720000, 'Riemannian geometry; the Riemann hypothesis'),
  P('Srinivasa Ramanujan', 'Mathematics', 'India', 760000, 'Self-taught genius of number theory'),
  P('Henri Poincaré', 'Mathematics', 'France', 720000, 'Founder of topology and chaos theory'),
  P('David Hilbert', 'Mathematics', 'Germany', 700000, 'Set the 23 problems that shaped 20th-century math'),
  P('Emmy Noether', 'Mathematics', 'Germany', 640000, 'Revolutionized abstract algebra and physics'),
  P('Alexander Grothendieck', 'Mathematics', 'France', 700000, 'Reinvented algebraic geometry'),
  P('Paul Erdős', 'Mathematics', 'Hungary', 620000, 'Most prolific collaborator in mathematics'),
  P('Terence Tao', 'Mathematics', 'Australia', 720000, 'Fields Medalist; "the Mozart of math"'),
  P('Grigori Perelman', 'Mathematics', 'Russia', 700000, 'Proved the Poincaré conjecture'),
  P('Andrew Wiles', 'Mathematics', 'United Kingdom', 680000, 'Proved Fermat\'s Last Theorem'),
  P('Évariste Galois', 'Mathematics', 'France', 620000, 'Founder of group theory, at age 20'),
  P('Pierre de Fermat', 'Mathematics', 'France', 640000, 'Founder of number theory and probability'),
  P('Blaise Pascal', 'Mathematics', 'France', 620000, 'Co-founder of probability theory'),
  P('Georg Cantor', 'Mathematics', 'Germany', 620000, 'Founder of set theory'),
  P('Kurt Gödel', 'Mathematics', 'Austria', 700000, 'The incompleteness theorems'),
  P('Benoit Mandelbrot', 'Mathematics', 'France', 560000, 'Father of fractal geometry; finance modelling'),
  P('Maryam Mirzakhani', 'Mathematics', 'Iran', 620000, 'First woman to win the Fields Medal'),
  P('Emmy Nöther', 'Mathematics', 'Germany', 20000, 'placeholder-dedupe'),
  P('Al-Khwarizmi', 'Mathematics', 'Uzbekistan', 720000, 'Father of algebra; the word "algorithm"'),
  P('Omar Khayyam', 'Mathematics', 'Iran', 480000, 'Solved cubic equations; poet-mathematician'),
  P('Ada Lovelace', 'Computer Science', 'United Kingdom', 620000, 'The first computer programmer'),

  // ── Computer scientists & technologists ──────────────────────────────
  P('Alan Turing', 'Computer Science', 'United Kingdom', 940000, 'Father of computer science and AI'),
  P('John von Neumann', 'Computer Science', 'Hungary', 980000, 'Von Neumann architecture; game theory; polymath'),
  P('Claude Shannon', 'Computer Science', 'United States', 820000, 'Father of information theory'),
  P('Donald Knuth', 'Computer Science', 'United States', 700000, 'The Art of Computer Programming; TeX'),
  P('Dennis Ritchie', 'Computer Science', 'United States', 720000, 'Created C and co-created Unix'),
  P('Ken Thompson', 'Computer Science', 'United States', 700000, 'Co-created Unix and Go'),
  P('Tim Berners-Lee', 'Computer Science', 'United Kingdom', 820000, 'Invented the World Wide Web'),
  P('Vint Cerf', 'Computer Science', 'United States', 640000, 'Co-designed TCP/IP; "father of the Internet"'),
  P('Linus Torvalds', 'Computer Science', 'Finland', 700000, 'Created Linux and Git'),
  P('Grace Hopper', 'Computer Science', 'United States', 640000, 'Pioneered compilers; COBOL'),
  P('Edsger Dijkstra', 'Computer Science', 'Netherlands', 620000, 'Shortest-path algorithm; structured programming'),
  P('Geoffrey Hinton', 'Computer Science', 'Canada', 720000, 'Godfather of deep learning; Turing Award'),
  P('Yann LeCun', 'Computer Science', 'France', 600000, 'Pioneer of convolutional neural networks'),
  P('Yoshua Bengio', 'Computer Science', 'Canada', 600000, 'Deep-learning pioneer; Turing Award'),
  P('Andrew Ng', 'Computer Science', 'United States', 480000, 'Co-founder of Coursera & Google Brain'),
  P('Demis Hassabis', 'Computer Science', 'United Kingdom', 620000, 'Co-founder & CEO of DeepMind; Nobel laureate'),
  P('Ilya Sutskever', 'Computer Science', 'Canada', 480000, 'Co-founder & former chief scientist of OpenAI'),
  P('Jeff Dean', 'Computer Science', 'United States', 520000, 'Chief scientist at Google; MapReduce & TensorFlow'),
  P('Fei-Fei Li', 'Computer Science', 'United States', 460000, 'Created ImageNet; pioneer of computer vision'),
  P('Guido van Rossum', 'Computer Science', 'Netherlands', 520000, 'Creator of Python'),
  P('James Gosling', 'Computer Science', 'Canada', 460000, 'Creator of Java'),
  P('Bjarne Stroustrup', 'Computer Science', 'Denmark', 460000, 'Creator of C++'),
  P('Jensen Huang (Tech)', 'Computer Science', 'United States', 20000, 'placeholder-dedupe'),

  // ── Fintech & crypto ─────────────────────────────────────────────────
  P('Satoshi Nakamoto', 'Entrepreneurship', 'Unknown', 820000, 'Pseudonymous creator of Bitcoin'),
  P('Vitalik Buterin', 'Entrepreneurship', 'Canada', 620000, 'Co-founder of Ethereum'),
  P('Changpeng Zhao', 'Entrepreneurship', 'Canada', 480000, 'Founder of Binance'),
  P('Brian Armstrong', 'Entrepreneurship', 'United States', 420000, 'Co-founder & CEO of Coinbase'),
  P('Michael Saylor', 'Entrepreneurship', 'United States', 340000, 'Executive chairman of MicroStrategy; Bitcoin advocate'),
  P('Max Levchin', 'Entrepreneurship', 'Ukraine', 320000, 'Co-founder of PayPal and Affirm'),
  P('Nikolay Storonsky', 'Entrepreneurship', 'United Kingdom', 340000, 'Co-founder & CEO of Revolut'),
  P('Kristo Käärmann', 'Entrepreneurship', 'Estonia', 260000, 'Co-founder & CEO of Wise'),
  P('Vlad Tenev', 'Entrepreneurship', 'Bulgaria', 260000, 'Co-founder & CEO of Robinhood'),

  // ── Trading & markets figures ────────────────────────────────────────
  P('Jesse Livermore', 'Quant / Trading', 'United States', 420000, 'Legendary speculator of the early 20th century'),
  P('Richard Dennis', 'Quant / Trading', 'United States', 280000, 'Ran the Turtle Traders experiment'),
  P('Larry Williams', 'Quant / Trading', 'United States', 180000, 'Record-setting futures trader and author'),
  P('Linda Raschke', 'Quant / Trading', 'United States', 160000, 'Veteran short-term trader; Market Wizards'),
  P('Paul Rotter', 'Quant / Trading', 'Germany', 120000, 'One of the most successful order-book traders'),
  P('Bill Lipschutz', 'Quant / Trading', 'United States', 180000, 'Legendary FX trader at Salomon Brothers'),
  P('Andrew Krieger', 'Quant / Trading', 'United States', 150000, 'Made $300M shorting the NZ dollar in 1987'),
  P('Michael Burry', 'Investing', 'United States', 380000, 'Founder of Scion; called the 2008 crash'),
  P('Cathie Wood', 'Investing', 'United States', 300000, 'Founder & CEO of ARK Invest'),
  P('Peter Brandt', 'Quant / Trading', 'United States', 140000, 'Veteran classical-charting trader'),

  // ── LixCap (researched) ──────────────────────────────────────────────
  P('William Fellows', 'Private Equity', 'United States', 90000, 'Co-founder & Executive Managing Director of LixCap; 24+ yrs, Johns Hopkins SAIS'),
  P('Samir Belrhandoria', 'Private Equity', 'Morocco', 78000, 'Managed the €80M Moroccan Infrastructure Fund; energy & infrastructure investor'),
  P('Yassine Benidder', 'Private Equity', 'Morocco', 62000, 'Leads the Financial Advisory practice at LixCap; 10+ yrs in PE & advisory'),

  // ── ISCAE professors & researchers (researched where available) ──────
  P('Inass El Farissi', 'Academia', 'Morocco', 72000, 'ISCAE professor; created the Specialized Master in Finance; double doctorate'),
  P('Selma Haj Khlifa', 'Academia', 'Morocco', 70000, 'ISCAE professor-researcher; HDR in Banking & Finance; L\'Économiste research prize 2017'),
  P('Mohamed Amine Issami', 'Academia', 'Morocco', 46000, 'ISCAE professor & researcher in finance'),
  P('Younes Lahrichi', 'Academia', 'Morocco', 46000, 'ISCAE professor & researcher in finance'),
  P('Salma Echcharqy', 'Academia', 'Morocco', 44000, 'ISCAE professor & researcher in management'),
  P('Jihane Aayale', 'Academia', 'Morocco', 44000, 'ISCAE professor & researcher'),
  P('Adil Bami', 'Academia', 'Morocco', 44000, 'ISCAE professor & researcher'),
  P('Halima Baghad', 'Academia', 'Morocco', 44000, 'ISCAE professor & researcher'),
  P('Imane Boudri', 'Academia', 'Morocco', 44000, 'ISCAE professor & researcher'),
  P('Meriem Bouyzem', 'Academia', 'Morocco', 44000, 'ISCAE professor & researcher'),
  P('Meriem Seffar', 'Academia', 'Morocco', 44000, 'ISCAE professor & researcher'),
  P('Amine Zenjari', 'Academia', 'Morocco', 44000, 'ISCAE professor & researcher'),

  // ── Management & operators ───────────────────────────────────────────
  P('Jack Welch', 'Management', 'United States', 480000, 'Legendary CEO of General Electric'),
  P('Indra Nooyi', 'Management', 'India', 400000, 'Former Chairman & CEO of PepsiCo'),
  P('Mary Barra', 'Management', 'United States', 380000, 'Chair & CEO of General Motors'),
  P('Sheryl Sandberg', 'Management', 'United States', 380000, 'Former COO of Meta; author of Lean In'),
  P('Ginni Rometty', 'Management', 'United States', 300000, 'Former Chairman & CEO of IBM'),
  P('Alan Mulally', 'Management', 'United States', 300000, 'Turned around Ford Motor Company'),
  P('Carlos Ghosn', 'Management', 'Brazil', 200000, 'Former chairman of Renault-Nissan-Mitsubishi'),
  P('Bob Iger', 'Management', 'United States', 420000, 'CEO of The Walt Disney Company'),
  P('Doug McMillon', 'Management', 'United States', 320000, 'CEO of Walmart'),
];

// A few placeholder-dedupe rows were kept above to preserve source-of-truth
// ordering during authoring; strip any that leaked in and de-dupe by name.
const _seen = new Set();
const CLEAN = PERSONALITIES.filter((p) => {
  if (p.note === 'placeholder-dedupe') return false;
  const key = p.name.toLowerCase();
  if (_seen.has(key)) return false;
  _seen.add(key);
  return true;
});

export const LEADERBOARD = CLEAN.sort((a, b) => b.xp - a.xp);

export const PERSONALITY_DOMAINS = [...new Set(LEADERBOARD.map((p) => p.domain))].sort();
export const PERSONALITY_COUNTRIES = [...new Set(LEADERBOARD.map((p) => p.country))].sort();
